artifact_uri: file:D:/Folder/My Folder/PROJECTS/Fraud Detection System/mlflow/0/a383645452cb414ba61629e1e6b50692/artifacts
end_time: 1733401627783
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a383645452cb414ba61629e1e6b50692
run_name: unleashed-snipe-519
run_uuid: a383645452cb414ba61629e1e6b50692
source_name: ''
source_type: 4
source_version: ''
start_time: 1733401616843
status: 3
tags: []
user_id: prasa
