artifact_location: file:D:/Folder/My Folder/PROJECTS/Fraud Detection System/mlflow/0
creation_time: 1733378248896
experiment_id: '0'
last_update_time: 1733378248896
lifecycle_stage: active
name: Default
