artifact_location: file:D:/Folder/My Folder/PROJECTS/Fraud Detection System/mlflow/501860454071534842
creation_time: 1733378248917
experiment_id: '501860454071534842'
last_update_time: 1733378248917
lifecycle_stage: active
name: Fraud Detection Experiment
