artifact_uri: file:D:/Folder/My Folder/PROJECTS/Fraud Detection System/mlflow/0/ae8939ee821942039362dfb0b5bd2368/artifacts
end_time: 1733401192174
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ae8939ee821942039362dfb0b5bd2368
run_name: colorful-mole-626
run_uuid: ae8939ee821942039362dfb0b5bd2368
source_name: ''
source_type: 4
source_version: ''
start_time: 1733401192096
status: 3
tags: []
user_id: prasa
